### PR TITLE
Issue #77 - Switch to graph version 2.0

### PR DESCRIPTION
**Pull request by hermanbosma**

### CODE REVIEW

**Comment by capaj** [comment]
why would author not merge this in?

**Comment by criso** [comment]
@capaj - https://github.com/criso/fbgraph/issues/76

**Comment by criso** [comment]
So, "The current, latest version of the Graph API is v2.3. Apps calling v1.0 have until April 30, 2015 to upgrade to v2.0 or later."

How about this rolls out after 4/30/15 ?

**Comment by tleunen** [comment]
The apps are automatically upgraded to at least 2.0 when they try to make calls with 1.0. So that's fine.

Also, I think the new default version should be 2.3 and not 2.0.

**Comment by criso** [comment]
Makes sense - kinda spaced out this. I'll merge and roll out a new version as soon as I get a minute :smiley_cat:

**Pull request merged**
